services:
  postgres:
    image: postgres:15
    container_name: poker_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poker_db
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: node:20
    container_name: api_poker
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - .:/app         # monte tout ton code dans /app
      - /app/node_modules   # Ã©vite de remplacer node_modules par ceux du host
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: poker_db
      NODE_ENV: development

volumes:
  postgres_data:
